version: '3.1'
services:
  superset:
    restart: unless-stopped
    env_file: .env
    build:
      context: ./
    ports:
      - 8088:8088
    volumes:
      - ./data:/app/superset_home
