version: '3'
services:
  minio:
    build: ./minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: SingleStore1!
volumes:
  data: